using System.Collections.Generic;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace MqttDashboard.SourceGenerators;

/// <summary>
/// Incremental source generator that reads wwwroot/mqttdashboard-icon.svg
/// (registered as an AdditionalFile in MqttDashboard.Client.csproj) and emits
/// AppIcons.cs containing the inner SVG elements as a C# string constant for
/// use with MudBlazor's Icon parameter.
///
/// Fill/stroke colour values are replaced with "currentColor" so the MudBlazor
/// Color parameter controls the rendered colour.
///
/// To update the icon: edit mqttdashboard-icon.svg and rebuild — no manual
/// file editing or script execution needed.
/// </summary>
[Generator]
public sealed class AppIconsGenerator : IIncrementalGenerator
{
    private static readonly string[] _shapeElements =
        new[] { "rect", "line", "circle", "path", "polygon", "polyline", "ellipse" };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var svgFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("mqttdashboard-icon.svg",
                System.StringComparison.OrdinalIgnoreCase));

        var iconContent = svgFiles.Select((file, ct) =>
        {
            var text = file.GetText(ct)?.ToString();
            return text is null ? null : ExtractMudBlazorIconString(text);
        });

        context.RegisterSourceOutput(iconContent, (ctx, inner) =>
        {
            if (inner is null) return;
            ctx.AddSource("AppIcons.g.cs", BuildSourceText(inner));
        });
    }

    /// <summary>
    /// Parses the SVG, filters out background/invisible elements, and returns
    /// the inner markup with all fill/stroke colours replaced by "currentColor".
    /// </summary>
    private static string ExtractMudBlazorIconString(string svgText)
    {
        var doc = XDocument.Parse(svgText);
        var root = doc.Root;
        if (root is null) return string.Empty;

        var lines = new List<string>();

        foreach (var el in root.Elements())
        {
            var localName = el.Name.LocalName;

            if (!IsShapeElement(localName)) continue;

            // Skip background/transparent rects (width/height="100%" or opacity="0")
            if (localName == "rect")
            {
                var w = el.Attribute("width")?.Value ?? "";
                var h = el.Attribute("height")?.Value ?? "";
                var op = el.Attribute("opacity")?.Value ?? "";
                if (w.Contains('%') || h.Contains('%') || op == "0") continue;
            }

            lines.Add(SerialiseElement(el));
        }

        return string.Join("\n        ", lines);
    }

    private static bool IsShapeElement(string name)
    {
        foreach (var s in _shapeElements)
            if (s == name) return true;
        return false;
    }

    /// <summary>
    /// Serialises an XElement to a self-closing SVG tag string, replacing any
    /// fill/stroke colour values (non-"none", non-empty) with "currentColor".
    /// </summary>
    private static string SerialiseElement(XElement el)
    {
        var sb = new StringBuilder();
        sb.Append('<');
        sb.Append(el.Name.LocalName);

        foreach (var attr in el.Attributes())
        {
            sb.Append(' ');
            sb.Append(attr.Name.LocalName);
            sb.Append("=\"");

            var val = attr.Value;
            if ((attr.Name.LocalName == "fill" || attr.Name.LocalName == "stroke")
                && val.Length > 0 && val != "none")
            {
                val = "currentColor";
            }

            sb.Append(val);
            sb.Append('"');
        }

        sb.Append(" />");
        return sb.ToString();
    }

    private static string BuildSourceText(string innerElements)
    {
        // Build with StringBuilder — avoids nesting raw string literals which
        // would prematurely terminate the outer $$"""...""" delimiter.
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by MqttDashboard.SourceGenerators.AppIconsGenerator");
        sb.AppendLine("//   from wwwroot/mqttdashboard-icon.svg -- do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace MqttDashboard;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Custom SVG icon strings for MudBlazor's Icon parameter.");
        sb.AppendLine("/// Rendered inside &lt;svg viewBox=\"0 0 24 24\"&gt; by MudIcon/MudIconButton.");
        sb.AppendLine("/// Colours use \"currentColor\" so the MudBlazor Color parameter is respected.");
        sb.AppendLine("/// Geometry is sourced from wwwroot/mqttdashboard-icon.svg via source generation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class AppIcons");
        sb.AppendLine("{");
        sb.AppendLine("    public const string MqttDashboard =");
        sb.AppendLine("        \"\"\"");
        sb.AppendLine("        " + innerElements);
        sb.AppendLine("        \"\"\";");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
